
export const sauceRecipes = [
    {
        id: 'Cheese Sauce',
        name: 'Vegan Nacho Cheese Sauce',
        image: '../assets/VeganCheesesauce.png',
        description: 'Do you want cheese, and NACHOS? But you are eating a plant-based diet? This sauce will be your new favorite recipe, guaranteed!!',
        recipe: 'https://www.noracooks.com/easy-vegan-nacho-cheese-sauce',
        category: 'sauce',
        happyprice: 5,
        price: 7
    },
    { id: 'Tali Sauce',
        name: 'Tali Sauce - As seen at \'The Whole Bowl\'',
        image: '../assets/Tali Sauce.png',
        description: 'If you haven\'t been to the WHole Bowl yet, well then you are missing it all! A spicy, garlicy, lemony, umami sauce that will make you fall in love with nutritional yeast.',
        recipe: 'https://sweetphi.com/the-whole-bowl-tali-sauce-recipe-vegetarian-gluten-free/',
        category: 'sauce',
        happyprice: 4, 
        price: 6,
    },
    { id: 'Ajvar',
        name: 'Ajvar',
        image: '../assets/ajvar.png',
        description: 'Who knew that a combination of eggplant, roasted red pepper, garlic, and some other good spices could make a sauce fitting for just about any dish? Try it with goat cheese!',
        recipe: 'https://saltandwind.com/recipes/370-ajvar-roasted-pepper-and-eggplant-dip-recipe',
        category: 'sauce',
        happyprice: 4,
        price: 5,
    }, 
    { id: 'Tobys',
        name: 'Toby\'s Tofu Pate',
        image: '../assets/Tobys.png',
        description: 'It goes with anything, it replaces egg salad, it disappears before you knew it! Add a jalapeno for a kick!',
        recipe: 'http://www.bowenappetit.com/2013/08/11/homemade-tobys-tofu-pate/',
        category: 'sauce',
        happyprice: 5,
        price: 6 
    },
    { id: 'mole',
        name: 'Holy Mole Sauce',
        image: '../assets/Mole.png',
        description: 'Do you cook with it, use it as a marinade, dip chips in like a salsa? yes, yes, and YES!',
        recipe: 'https://www.gimmesomeoven.com/holy-mole-sauce/',
        category: 'sauce',
        happyprice: 4,
        price: 5,
    },
    { id: 'chocolate',
        name: 'Homemade Chocolate Sauce',
        image: '../assets/Chocolate Sauce.png',
        description: 'Who needs Hersheys when it is this easy to make your own chocolate syrup? Be careful though, you\'ll put it in everything!',
        recipe: 'https://barefeetinthekitchen.com/simple-homemade-chocolate-sauce/',
        category: 'sauce',
        happyprice: 4,
        price: 3.5,
    },
];